apiVersion: kueue.x-k8s.io/v1beta2
kind: ResourceFlavor
metadata:
  name: hami-t4
spec:
  nodeLabels:
    nvidia.com/gpu.product: Tesla-T4
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: ClusterQueue
metadata:
  name: hami-cq
spec:
  namespaceSelector: {}
  resourceGroups:
    - coveredResources:
        - nvidia.com/gpu
        - nvidia.com/total-gpumem
        - nvidia.com/total-gpucores
      flavors:
        - name: hami-t4
          resources:
            - name: nvidia.com/gpu
              nominalQuota: 2
            - name: nvidia.com/total-gpumem
              nominalQuota: 8192
            - name: nvidia.com/total-gpucores
              nominalQuota: 100
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: LocalQueue
metadata:
  name: hami-queue
  namespace: hami-kueue-demo
spec:
  clusterQueue: hami-cq
