# Source: https://github.com/Project-HAMi/k8s-dra-driver (demo/yaml/pod-0.yaml)
---
apiVersion: v1
kind: Pod
metadata:
  namespace: test-dra
  name: pod-0
spec:
  containers:
    - name: ctr0
      image: ubuntu:24.04
      command: ["bash", "-c"]
      args: ["export; trap 'exit 0' TERM; sleep 9999 & wait"]
      resources:
        requests:
          cpu: 1
        limits:
          cpu: 1
        claims:
          - name: single-gpu
  resourceClaims:
    - name: single-gpu
      resourceClaimName: single-gpu-0
